// examples/src/vue/pages/Counter.vue
<script setup lang="ts">
import { ref } from "vue"
import { Link } from "@inertiajs/vue3"
import AppLayout from "../layouts/AppLayout.vue"

defineProps<{ router: string, counter: number }>()

const count = ref(0)
</script>

<template>
  <AppLayout>
    <div class="badge-row">
      <span class="badge vue">Vue 3</span>
      <span class="badge router">{{ router }}</span>
      <span class="badge router">{{ counter }}</span>
    </div>
    <h1>🔢 Counter</h1>

    <div class="card counter-card">
      <p class="hint">État client pur — réinitialisé à chaque navigation (comportement normal d'Inertia)</p>
      <div class="display">{{ count }}</div>
      <div class="controls">
        <button class="btn dec" @click="count--">−</button>
        <button class="btn reset" @click="count = 0">reset</button>
        <button class="btn inc" @click="count++">+</button>
      </div>
    </div>

    <p class="note">
      Navigue vers <Link href="/" class="link">Home</Link> puis reviens :
      le compteur sera remis à zéro (nouvelle instance de composant).
      C'est le comportement normal d'Inertia — l'état client ne persiste pas
      entre les navigations (contrairement à un store Pinia, lui persistant).
    </p>
  </AppLayout>
</template>

<style scoped>
.badge-row   { display: flex; gap: .5rem; margin-bottom: 1.2rem; }
.badge       { padding: .25rem .75rem; border-radius: 99px; font-size: .75rem; font-weight: 600; }
.badge.vue    { background: #42b88320; color: #42b883; border: 1px solid #42b88340; }
.badge.router { background: #6366f120; color: #6366f1; border: 1px solid #6366f140; }
h1           { font-size: 2.2rem; margin: 0 0 1.5rem; }
.card        { background: #fff; border: 1px solid #e4e4e7; border-radius: 10px; padding: 2rem; }
.counter-card { text-align: center; }
.hint        { color: #888; font-size: .85rem; margin: 0 0 1.5rem; }
.display     { font-size: 5rem; font-weight: 700; line-height: 1; margin-bottom: 1.5rem; color: #42b883; }
.controls    { display: flex; justify-content: center; gap: .75rem; }
.btn         { width: 48px; height: 48px; border: none; border-radius: 8px; font-size: 1.4rem;
               cursor: pointer; font-weight: 700; transition: all .12s; }
.btn.dec     { background: #fee2e2; color: #ef4444; }
.btn.dec:hover  { background: #ef4444; color: #fff; }
.btn.inc     { background: #dcfce7; color: #22c55e; }
.btn.inc:hover  { background: #22c55e; color: #fff; }
.btn.reset   { width: 72px; background: #f4f4f5; color: #666; font-size: .8rem; }
.btn.reset:hover { background: #e4e4e7; }
.note        { color: #666; line-height: 1.7; margin-top: 1.25rem; font-size: .9rem; }
.link        { color: #42b883; text-decoration: none; font-weight: 600; }
.link:hover  { text-decoration: underline; }
</style>

// examples/src/react/pages/Counter.tsx
import { useState } from "react"
import { Link } from "@inertiajs/react"
import AppLayout from "../layouts/AppLayout"

interface Props {
  router: string
}

export default function Counter({ router }: Props) {
  const [count, setCount] = useState(0)

  return (
    <AppLayout>
      <div style={s.badgeRow}>
        <span style={{ ...s.badge, ...s.badgeReact }}>React 18</span>
        <span style={{ ...s.badge, ...s.badgeRouter }}>{router}</span>
      </div>
      <h1 style={s.h1}>🔢 Counter</h1>

      <div style={s.card}>
        <p style={s.hint}>État client — survit aux navigations Inertia dans la même session</p>
        <div style={s.display}>{count}</div>
        <div style={s.controls}>
          <button style={{ ...s.btn, ...s.btnDec }} onClick={() => setCount(c => c - 1)}>−</button>
          <button style={{ ...s.btn, ...s.btnReset }} onClick={() => setCount(0)}>reset</button>
          <button style={{ ...s.btn, ...s.btnInc }} onClick={() => setCount(c => c + 1)}>+</button>
        </div>
      </div>

      <p style={s.note}>
        Navigue vers <Link href="/" style={s.link}>Home</Link> puis reviens :
        le compteur sera remis à zéro (nouvelle instance de composant).
        C'est le comportement normal d'Inertia — l'état client ne persiste pas
        entre les navigations (contrairement à un contexte React persistant).
      </p>
    </AppLayout>
  )
}

const s: Record<string, React.CSSProperties> = {
  badgeRow:    { display: "flex", gap: ".5rem", marginBottom: "1.2rem" },
  badge:       { padding: ".25rem .75rem", borderRadius: 99, fontSize: ".75rem", fontWeight: 600 },
  badgeReact:  { background: "#61dafb20", color: "#0ea5e9", border: "1px solid #61dafb40" },
  badgeRouter: { background: "#6366f120", color: "#6366f1", border: "1px solid #6366f140" },
  h1:          { fontSize: "2.2rem", margin: "0 0 1.5rem" },
  card:        { background: "#fff", border: "1px solid #e4e4e7", borderRadius: 10,
                 padding: "2rem", textAlign: "center" },
  hint:        { color: "#888", fontSize: ".85rem", margin: "0 0 1.5rem" },
  display:     { fontSize: "5rem", fontWeight: 700, lineHeight: 1, marginBottom: "1.5rem", color: "#0ea5e9" },
  controls:    { display: "flex", justifyContent: "center", gap: ".75rem" },
  btn:         { width: 48, height: 48, border: "none", borderRadius: 8, fontSize: "1.4rem",
                 cursor: "pointer", fontWeight: 700 },
  btnDec:      { background: "#fee2e2", color: "#ef4444" },
  btnInc:      { background: "#dcfce7", color: "#22c55e" },
  btnReset:    { width: 72, background: "#f4f4f5", color: "#666", fontSize: ".8rem" },
  note:        { color: "#666", lineHeight: 1.7, marginTop: "1.25rem", fontSize: ".9rem" },
  link:        { color: "#0ea5e9", textDecoration: "none", fontWeight: 600 },
}
